services:
  Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Writer:
    arguments:
      - '@Tailr\SuluTranslationsBundle\Domain\Command\WriteHandler'

  Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Loader:
    arguments:
      - '@Tailr\SuluTranslationsBundle\Domain\Repository\TranslationRepository'

  Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Remover:
    arguments:
      - '@Tailr\SuluTranslationsBundle\Domain\Command\RemoveHandler'

  Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\DatabaseProviderFactory:
    arguments:
      - '@Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Writer'
      - '@Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Loader'
      - '@Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Remover'
    tags:
      - { name: 'translation.provider_factory' }